version: "3.9"

services:
  master:
    build:
      context: app
      dockerfile: Dockerfile
  employee:
    build:
      context: app
      dockerfile: Dockerfile.employee
  payroll:
    build:
      context: app
      dockerfile: Dockerfile.payroll
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - master
    ports:
      - "80:80"