FROM python:3.8-slim-buster
WORKDIR /app
# Install dependencies:
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 3003
COPY payroll.py .
# Run the application:
CMD gunicorn --bind 0.0.0.0:3003 --timeout 600 -w 4 payroll:app 