FROM python:3.8-slim-buster
WORKDIR /app
# Install dependencies:
COPY requirements.txt .
RUN pip install -r requirements.txt
EXPOSE 3002
COPY employee.py .
# Run the application:
CMD gunicorn --bind 0.0.0.0:3002 --timeout 600 -w 4 employee:app 